name: Update

on: 
  repository_dispatch:
  workflow_dispatch:

# 定时触发编译
  schedule:
    - cron: 0 9 * * 5

# 点赞☆Star触发编译
#  watch:
#    types: [started]

jobs:
  Update:
    runs-on: ubuntu-20.04
    steps:
    - name: Clone Repository
      uses: actions/checkout@v3

    - name: Set git
      run : |
        git config --global user.email "jsjson@163.com"
        git config --global user.name "xiangfeidexiaohuo"
        sudo timedatectl set-timezone "Asia/Shanghai"

    - name: Delete workflow runs
      uses: xiangfeidexiaohuo/delete-workflow-runs@main
      continue-on-error: true
      with:
        retain_days: 1
        keep_minimum_runs: 0  
        
    - name: Update
      run: |

        rm -rf ./luci-app-onliner    
        rm -rf ./op-thunder/*


        svn export https://github.com/haiibo/packages/trunk/luci-app-onliner ./luci-app-onliner              
        svn export https://github.com/gngpp/thunder/trunk/openwrt/luci-app-thunder ./op-thunder/luci-app-thunder
        svn export https://github.com/gngpp/thunder/trunk/openwrt/thunder ./op-thunder/thunder
        
        
    - name: Apply
      run: |
        git add .
        git commit -m "Auto Sync: $(date +%Y-%m-%d" "%H:%M)"
        git push -f 
              
